### ISSUE TITLE
Add BERRY withdrawal/deposit contract (Pixels)

### ISSUE THREAD

**Issue by based64-eth** [roninbuilders/contracts#1]
Here's the contract: https://app.roninchain.com/token/0x1b918543b518e34902e1e8dd76052bee43c762ff

**Comment by based64-eth** [comment]
It seems like withdrawals and deposits work just by transferring tokens to/from this wallet: 0x3c3f3ea61c47c366e885e72435f441ef65148f53. There is no contract that users interact with.

**Comment by alexx855** [comment]
Its there! 

![image](https://github.com/roninbuilders/contracts/assets/1799851/638ae66e-86e3-476b-b9c5-0d4d9b14bdb1)

`import { BERRY } from '@roninbuilders/contracts'`

**Comment by alexx855** [comment]
Update to latest version just in case 😅

**Comment by alexx855** [comment]
@based64-eth update to the latest version just in case 😅
